use s17470

Alter PROCEDURE PROMOTESTUDENTS @STUDIES NVARCHAR(100), @SEMESTER INT
AS
BEGIN
		--SET XAC_ABORT ON;
		BEGIN TRAN
		DECLARE @IDSTUDIES INT = (SELECT IDSTUDY FROM STUDIES WHERE NAME = @STUDIES);
		IF @IDSTUDIES IS NULL
		BEGIN
			RAISERROR (15600,-1,-1, 'Studies not found.');  
			--RETURN;
		END

		DECLARE @IDENROLLMENT INT = (SELECT IDENROLLMENT FROM ENROLLMENT WHERE IDSTUDY = @IDSTUDIES AND SEMESTER = @SEMESTER);
		IF @IDENROLLMENT IS NULL
		BEGIN
			RAISERROR (15600,-1,-1, 'There are no students on this studies and semester.');  
		END

		DECLARE @NEW_IDENROLLMENT INT = (SELECT IDENROLLMENT FROM ENROLLMENT WHERE IDSTUDY = @IDSTUDIES AND SEMESTER = @SEMESTER+1)
		IF @NEW_IDENROLLMENT IS NULL
		BEGIN
			DECLARE @MAXENROLLMENT INT = (SELECT MAX(IDENROLLMENT) FROM ENROLLMENT);
			Set @NEW_IDENROLLMENT = @MAXENROLLMENT+1;
			INSERT INTO ENROLLMENT(IDENROLLMENT, SEMESTER, IDSTUDY, STARTDATE) VALUES (@NEW_IDENROLLMENT, @SEMESTER+1, @IDSTUDIES, '2020-09-30');

		END

		UPDATE STUDENT SET IDENROLLMENT = @NEW_IDENROLLMENT WHERE IDENROLLMENT = @IDENROLLMENT;
		COMMIT;
		SELECT * FROM ENROLLMENT WHERE IDENROLLMENT = @NEW_IDENROLLMENT;

		--SET  @OUTENROLL = @NEW_IDENROLLMENT;
		--PRINT @OUTENROLL;
	
		RETURN;
END;